// AUTO-GENERATED by scripts/gen-manifest.mjs — do not edit, do not commit conflicts by hand.
import type { FxKernel, FxMeta } from './types';


export interface ManifestEntry {
  meta: FxMeta;
  /** repo-relative path of the effect file (key for source loading) */
  effectPath: string;
  load: () => Promise<{ default: FxKernel }>;
}

export const manifest: ManifestEntry[] = [
];
