// AUTO-GENERATED by scripts/gen-manifest.mjs — do not edit, do not commit conflicts by hand.
import type { FxKernel, FxMeta } from './types';

import meta_A01 from '../../effects/audio/A01_waveform-bars.meta';
import meta_A02 from '../../effects/audio/A02_spectrum-analyzer.meta';
import meta_A03 from '../../effects/audio/A03_circular-viz.meta';
import meta_A04 from '../../effects/audio/A04_beat-pulse.meta';
import meta_A05 from '../../effects/audio/A05_oscilloscope.meta';
import meta_A06 from '../../effects/audio/A06_vu-meter.meta';
import meta_A07 from '../../effects/audio/A07_waveform-line.meta';
import meta_A08 from '../../effects/audio/A08_frequency-rings.meta';
import meta_A09 from '../../effects/audio/A09_amplitude-warp.meta';
import meta_A10 from '../../effects/audio/A10_beat-cut.meta';
import meta_B09 from '../../effects/broadcast/B09_news-ticker.meta';
import meta_B10 from '../../effects/broadcast/B10_countdown-clock.meta';
import meta_B11 from '../../effects/broadcast/B11_hud-frame.meta';
import meta_B12 from '../../effects/broadcast/B12_live-badge.meta';
import meta_B13 from '../../effects/broadcast/B13_quote-card.meta';
import meta_B14 from '../../effects/broadcast/B14_stat-callout.meta';
import meta_B15 from '../../effects/broadcast/B15_locator-pin.meta';
import meta_B16 from '../../effects/broadcast/B16_weather-panel.meta';
import meta_C01 from '../../effects/camera/C01_parallax-layers.meta';
import meta_C02 from '../../effects/camera/C02_ken-burns.meta';
import meta_C03 from '../../effects/camera/C03_handheld-shake.meta';
import meta_C04 from '../../effects/camera/C04_dolly-zoom.meta';
import meta_C05 from '../../effects/camera/C05_rack-focus.meta';
import meta_C06 from '../../effects/camera/C06_orbit-around.meta';
import meta_C07 from '../../effects/camera/C07_crash-zoom.meta';
import meta_C08 from '../../effects/camera/C08_tilt-shift.meta';
import meta_C09 from '../../effects/camera/C09_roll-horizon.meta';
import meta_C10 from '../../effects/camera/C10_depth-layers-3d.meta';
import meta_C11 from '../../effects/camera/C11_perspective-card.meta';
import meta_C12 from '../../effects/camera/C12_follow-track.meta';
import meta_D01 from '../../effects/distort/D01_displacement-wave.meta';
import meta_D02 from '../../effects/distort/D02_ripple-circle.meta';
import meta_D03 from '../../effects/distort/D03_twirl-vortex.meta';
import meta_D04 from '../../effects/distort/D04_bulge-pinch.meta';
import meta_D05 from '../../effects/distort/D05_wave-shear.meta';
import meta_D06 from '../../effects/distort/D06_lens-barrel.meta';
import meta_D07 from '../../effects/distort/D07_mesh-warp.meta';
import meta_D08 from '../../effects/distort/D08_melt-drip.meta';
import meta_D09 from '../../effects/distort/D09_turbulent-noise.meta';
import meta_D10 from '../../effects/distort/D10_fisheye.meta';
import meta_D11 from '../../effects/distort/D11_mirror-fold.meta';
import meta_D12 from '../../effects/distort/D12_kaleidoscope.meta';
import meta_D13 from '../../effects/distort/D13_polar-coord.meta';
import meta_D14 from '../../effects/distort/D14_time-displace.meta';
import meta_E01 from '../../effects/texture/E01_film-grain.meta';
import meta_E02 from '../../effects/texture/E02_halftone-dot.meta';
import meta_E03 from '../../effects/texture/E03_dither-bayer.meta';
import meta_E04 from '../../effects/texture/E04_paper-fiber.meta';
import meta_E05 from '../../effects/texture/E05_scan-print.meta';
import meta_E06 from '../../effects/texture/E06_duotone-map.meta';
import meta_E07 from '../../effects/texture/E07_posterize-step.meta';
import meta_E08 from '../../effects/texture/E08_cross-hatch.meta';
import meta_E09 from '../../effects/texture/E09_risograph.meta';
import meta_E10 from '../../effects/texture/E10_vignette-breathe.meta';
import meta_E11 from '../../effects/texture/E11_chromatic-grain.meta';
import meta_E12 from '../../effects/texture/E12_ascii-map.meta';
import meta_G01 from '../../effects/glitch/G01_rgb-split.meta';
import meta_G02 from '../../effects/glitch/G02_datamosh-slice.meta';
import meta_G03 from '../../effects/glitch/G03_crt-scanline.meta';
import meta_G04 from '../../effects/glitch/G04_signal-loss.meta';
import meta_G05 from '../../effects/glitch/G05_vhs-tracking.meta';
import meta_G06 from '../../effects/glitch/G06_pixel-sort.meta';
import meta_G07 from '../../effects/glitch/G07_block-corrupt.meta';
import meta_G08 from '../../effects/glitch/G08_bit-crush.meta';
import meta_G09 from '../../effects/glitch/G09_interlace-tear.meta';
import meta_G10 from '../../effects/glitch/G10_ghost-echo.meta';
import meta_G11 from '../../effects/glitch/G11_compression-artifact.meta';
import meta_G12 from '../../effects/glitch/G12_sync-roll.meta';
import meta_G13 from '../../effects/glitch/G13_color-bleed.meta';
import meta_G14 from '../../effects/glitch/G14_static-burst.meta';
import meta_G15 from '../../effects/glitch/G15_frame-drop.meta';
import meta_G16 from '../../effects/glitch/G16_chromatic-shear.meta';
import meta_L01 from '../../effects/light/L01_bloom-pulse.meta';
import meta_L02 from '../../effects/light/L02_specular-sweep.meta';
import meta_L03 from '../../effects/light/L03_neon-flicker.meta';
import meta_L04 from '../../effects/light/L04_anamorphic-flare.meta';
import meta_L05 from '../../effects/light/L05_god-rays.meta';
import meta_L06 from '../../effects/light/L06_light-leak.meta';
import meta_L07 from '../../effects/light/L07_caustics.meta';
import meta_L08 from '../../effects/light/L08_lightning-arc.meta';
import meta_L09 from '../../effects/light/L09_strobe-cut.meta';
import meta_L10 from '../../effects/light/L10_rim-light.meta';
import meta_L11 from '../../effects/light/L11_halation.meta';
import meta_L12 from '../../effects/light/L12_spotlight-track.meta';
import meta_L13 from '../../effects/light/L13_glow-trail.meta';
import meta_L14 from '../../effects/light/L14_prism-refract.meta';
import meta_M01 from '../../effects/mask/M01_shape-reveal.meta';
import meta_M02 from '../../effects/mask/M02_gradient-wipe.meta';
import meta_M03 from '../../effects/mask/M03_text-knockout.meta';
import meta_M04 from '../../effects/mask/M04_alpha-matte.meta';
import meta_M05 from '../../effects/mask/M05_spotlight-mask.meta';
import meta_M06 from '../../effects/mask/M06_brush-stroke.meta';
import meta_M07 from '../../effects/mask/M07_scribble-erase.meta';
import meta_M08 from '../../effects/mask/M08_blind-reveal.meta';
import meta_M09 from '../../effects/mask/M09_radial-unveil.meta';
import meta_M10 from '../../effects/mask/M10_follow-mask.meta';
import meta_M11 from '../../effects/mask/M11_split-mask.meta';
import meta_M12 from '../../effects/mask/M12_noise-dissolve.meta';
import meta_N01 from '../../effects/nature/N01_fire-flame.meta';
import meta_N02 from '../../effects/nature/N02_smoke-plume.meta';
import meta_N03 from '../../effects/nature/N03_water-surface.meta';
import meta_N04 from '../../effects/nature/N04_cloud-drift.meta';
import meta_N05 from '../../effects/nature/N05_rain-streak.meta';
import meta_N06 from '../../effects/nature/N06_wind-grass.meta';
import meta_N07 from '../../effects/nature/N07_aurora-wave.meta';
import meta_N08 from '../../effects/nature/N08_lightning-storm.meta';
import meta_N09 from '../../effects/nature/N09_sand-flow.meta';
import meta_N10 from '../../effects/nature/N10_bubble-rise.meta';
import meta_N11 from '../../effects/nature/N11_crystal-grow.meta';
import meta_N12 from '../../effects/nature/N12_erosion-fade.meta';
import meta_O01 from '../../effects/motion/O01_pop-in.meta';
import meta_O02 from '../../effects/motion/O02_drop-bounce.meta';
import meta_O03 from '../../effects/motion/O03_swing-in.meta';
import meta_O04 from '../../effects/motion/O04_flip-reveal.meta';
import meta_O05 from '../../effects/motion/O05_slide-snap.meta';
import meta_O06 from '../../effects/motion/O06_fold-unfold.meta';
import meta_O07 from '../../effects/motion/O07_focus-pop.meta';
import meta_O08 from '../../effects/motion/O08_peel-in.meta';
import meta_O09 from '../../effects/motion/O09_jelly-wobble.meta';
import meta_O10 from '../../effects/motion/O10_pendulum-swing.meta';
import meta_O11 from '../../effects/motion/O11_spring-chain.meta';
import meta_O12 from '../../effects/motion/O12_gravity-toss.meta';
import meta_O13 from '../../effects/motion/O13_magnetic-snap.meta';
import meta_O14 from '../../effects/motion/O14_rubber-band.meta';
import meta_O15 from '../../effects/motion/O15_inertia-drift.meta';
import meta_O16 from '../../effects/motion/O16_float-hover.meta';
import meta_O17 from '../../effects/motion/O17_breathe-pulse.meta';
import meta_O18 from '../../effects/motion/O18_self-orbit.meta';
import meta_O19 from '../../effects/motion/O19_tilt-sway.meta';
import meta_O20 from '../../effects/motion/O20_heartbeat.meta';
import meta_O21 from '../../effects/motion/O21_attention-shake.meta';
import meta_O22 from '../../effects/motion/O22_tada-burst.meta';
import meta_O23 from '../../effects/motion/O23_stamp-slam.meta';
import meta_O24 from '../../effects/motion/O24_ring-focus.meta';
import meta_O25 from '../../effects/motion/O25_glitch-pop.meta';
import meta_P01 from '../../effects/particle/P01_particle-burst.meta';
import meta_P02 from '../../effects/particle/P02_confetti-rain.meta';
import meta_P03 from '../../effects/particle/P03_spark-shower.meta';
import meta_P04 from '../../effects/particle/P04_dust-motes.meta';
import meta_P05 from '../../effects/particle/P05_bokeh-drift.meta';
import meta_P06 from '../../effects/particle/P06_snow-fall.meta';
import meta_P07 from '../../effects/particle/P07_ember-rise.meta';
import meta_P08 from '../../effects/particle/P08_swarm-flock.meta';
import meta_P09 from '../../effects/particle/P09_magnetic-field.meta';
import meta_P10 from '../../effects/particle/P10_orbit-ring.meta';
import meta_P11 from '../../effects/particle/P11_trail-emitter.meta';
import meta_P12 from '../../effects/particle/P12_explosion-debris.meta';
import meta_P13 from '../../effects/particle/P13_attract-repel.meta';
import meta_P14 from '../../effects/particle/P14_point-cloud-form.meta';
import meta_Q01 from '../../effects/liquid/Q01_metaball-merge.meta';
import meta_Q02 from '../../effects/liquid/Q02_ink-diffuse.meta';
import meta_Q03 from '../../effects/liquid/Q03_paint-splatter.meta';
import meta_Q04 from '../../effects/liquid/Q04_viscous-drip.meta';
import meta_Q05 from '../../effects/liquid/Q05_fluid-sim.meta';
import meta_Q06 from '../../effects/liquid/Q06_wave-tank.meta';
import meta_Q07 from '../../effects/liquid/Q07_oil-slick.meta';
import meta_Q08 from '../../effects/liquid/Q08_gel-wobble.meta';
import meta_Q09 from '../../effects/liquid/Q09_foam-bubble.meta';
import meta_Q10 from '../../effects/liquid/Q10_liquid-fill.meta';
import meta_R01 from '../../effects/pattern/R01_perlin-field.meta';
import meta_R02 from '../../effects/pattern/R02_flow-field.meta';
import meta_R03 from '../../effects/pattern/R03_cellular-automata.meta';
import meta_R04 from '../../effects/pattern/R04_reaction-diffusion.meta';
import meta_R05 from '../../effects/pattern/R05_moire-interference.meta';
import meta_R06 from '../../effects/pattern/R06_wave-interference.meta';
import meta_R07 from '../../effects/pattern/R07_lissajous.meta';
import meta_R08 from '../../effects/pattern/R08_phyllotaxis.meta';
import meta_R09 from '../../effects/pattern/R09_maze-generate.meta';
import meta_R10 from '../../effects/pattern/R10_stripe-shift.meta';
import meta_R11 from '../../effects/pattern/R11_checker-flip.meta';
import meta_R12 from '../../effects/pattern/R12_hex-grid-pulse.meta';
import meta_R13 from '../../effects/pattern/R13_dot-matrix.meta';
import meta_R14 from '../../effects/pattern/R14_chladni-figure.meta';
import meta_S01 from '../../effects/shape/S01_stroke-draw.meta';
import meta_S02 from '../../effects/shape/S02_blob-morph.meta';
import meta_S03 from '../../effects/shape/S03_grid-wave.meta';
import meta_S04 from '../../effects/shape/S04_radar-sweep.meta';
import meta_S05 from '../../effects/shape/S05_polygon-rotate.meta';
import meta_S06 from '../../effects/shape/S06_circle-pack.meta';
import meta_S07 from '../../effects/shape/S07_voronoi-shatter.meta';
import meta_S08 from '../../effects/shape/S08_triangulate.meta';
import meta_S09 from '../../effects/shape/S09_spiral-unfold.meta';
import meta_S10 from '../../effects/shape/S10_fractal-branch.meta';
import meta_S11 from '../../effects/shape/S11_boolean-merge.meta';
import meta_S12 from '../../effects/shape/S12_dash-march.meta';
import meta_S13 from '../../effects/shape/S13_corner-trace.meta';
import meta_S14 from '../../effects/shape/S14_concentric-pulse.meta';
import meta_S15 from '../../effects/shape/S15_isometric-stack.meta';
import meta_S16 from '../../effects/shape/S16_truchet-tile.meta';
import meta_T01 from '../../effects/type/T01_kinetic-split.meta';
import meta_T02 from '../../effects/type/T02_scramble-decode.meta';
import meta_T03 from '../../effects/type/T03_odometer-roll.meta';
import meta_T04 from '../../effects/type/T04_mask-reveal.meta';
import meta_T05 from '../../effects/type/T05_typewriter-caret.meta';
import meta_T06 from '../../effects/type/T06_word-cascade.meta';
import meta_T07 from '../../effects/type/T07_variable-weight-morph.meta';
import meta_T08 from '../../effects/type/T08_text-path-flow.meta';
import meta_T09 from '../../effects/type/T09_char-flip-3d.meta';
import meta_T10 from '../../effects/type/T10_highlight-sweep.meta';
import meta_T11 from '../../effects/type/T11_stretch-squash.meta';
import meta_T12 from '../../effects/type/T12_vertical-roll.meta';
import meta_T13 from '../../effects/type/T13_outline-fill.meta';
import meta_T14 from '../../effects/type/T14_letter-explode.meta';
import meta_T15 from '../../effects/type/T15_wave-text.meta';
import meta_T16 from '../../effects/type/T16_justify-snap.meta';
import meta_T17 from '../../effects/type/T17_char-bounce-wave.meta';
import meta_T18 from '../../effects/type/T18_char-swarm-assemble.meta';
import meta_T19 from '../../effects/type/T19_word-swap-roll.meta';
import meta_T20 from '../../effects/type/T20_char-gravity-fall.meta';
import meta_T21 from '../../effects/type/T21_elastic-tracking.meta';
import meta_U01 from '../../effects/ui/U01_terminal-boot.meta';
import meta_U02 from '../../effects/ui/U02_toggle-switch.meta';
import meta_U03 from '../../effects/ui/U03_loading-spinner.meta';
import meta_U04 from '../../effects/ui/U04_skeleton-shimmer.meta';
import meta_U05 from '../../effects/ui/U05_notification-stack.meta';
import meta_U06 from '../../effects/ui/U06_tab-slide.meta';
import meta_U07 from '../../effects/ui/U07_modal-spring.meta';
import meta_U08 from '../../effects/ui/U08_cursor-trace.meta';
import meta_U09 from '../../effects/ui/U09_keyboard-press.meta';
import meta_U10 from '../../effects/ui/U10_chip-filter.meta';
import meta_U11 from '../../effects/ui/U11_accordion-expand.meta';
import meta_U12 from '../../effects/ui/U12_drag-sort.meta';
import meta_V01 from '../../effects/data/V01_bar-race.meta';
import meta_V02 from '../../effects/data/V02_counter-odometer.meta';
import meta_V03 from '../../effects/data/V03_progress-ring.meta';
import meta_V04 from '../../effects/data/V04_line-chart-draw.meta';
import meta_V05 from '../../effects/data/V05_pie-sweep.meta';
import meta_V06 from '../../effects/data/V06_sparkline-scroll.meta';
import meta_V07 from '../../effects/data/V07_heatmap-fill.meta';
import meta_V08 from '../../effects/data/V08_node-graph.meta';
import meta_V09 from '../../effects/data/V09_gauge-needle.meta';
import meta_V10 from '../../effects/data/V10_stacked-grow.meta';
import meta_V11 from '../../effects/data/V11_scatter-settle.meta';
import meta_V12 from '../../effects/data/V12_sankey-flow.meta';
import meta_V13 from '../../effects/data/V13_tree-expand.meta';
import meta_V14 from '../../effects/data/V14_timeline-scrub.meta';
import meta_X01 from '../../effects/trans/X01_iris-wipe.meta';
import meta_X02 from '../../effects/trans/X02_slice-shuffle.meta';
import meta_X03 from '../../effects/trans/X03_zoom-punch.meta';
import meta_X04 from '../../effects/trans/X04_ink-bleed.meta';
import meta_X05 from '../../effects/trans/X05_push-slide.meta';
import meta_X06 from '../../effects/trans/X06_clock-wipe.meta';
import meta_X07 from '../../effects/trans/X07_page-curl.meta';
import meta_X08 from '../../effects/trans/X08_blinds.meta';
import meta_X09 from '../../effects/trans/X09_pixelate-cross.meta';
import meta_X10 from '../../effects/trans/X10_morph-cut.meta';
import meta_X11 from '../../effects/trans/X11_shatter-break.meta';
import meta_X12 from '../../effects/trans/X12_liquid-warp.meta';
import meta_X13 from '../../effects/trans/X13_cube-rotate.meta';
import meta_X14 from '../../effects/trans/X14_whip-pan.meta';
import meta_X15 from '../../effects/trans/X15_luma-wipe.meta';
import meta_X16 from '../../effects/trans/X16_split-open.meta';
import meta_Y07 from '../../effects/stylize/Y07_ink-outline.meta';
import meta_Y08 from '../../effects/stylize/Y08_hatch-shade.meta';
import meta_Y09 from '../../effects/stylize/Y09_stipple-dots.meta';
import meta_Y10 from '../../effects/stylize/Y10_mosaic-tiles.meta';
import meta_Y11 from '../../effects/stylize/Y11_stained-glass.meta';
import meta_Y12 from '../../effects/stylize/Y12_paper-cutout.meta';

export interface ManifestEntry {
  meta: FxMeta;
  /** repo-relative path of the effect file (key for source loading) */
  effectPath: string;
  load: () => Promise<{ default: FxKernel }>;
}

export const manifest: ManifestEntry[] = [
  { meta: meta_A01, effectPath: 'effects/audio/A01_waveform-bars.effect.ts', load: () => import('../../effects/audio/A01_waveform-bars.effect') },
  { meta: meta_A02, effectPath: 'effects/audio/A02_spectrum-analyzer.effect.ts', load: () => import('../../effects/audio/A02_spectrum-analyzer.effect') },
  { meta: meta_A03, effectPath: 'effects/audio/A03_circular-viz.effect.ts', load: () => import('../../effects/audio/A03_circular-viz.effect') },
  { meta: meta_A04, effectPath: 'effects/audio/A04_beat-pulse.effect.tsx', load: () => import('../../effects/audio/A04_beat-pulse.effect') },
  { meta: meta_A05, effectPath: 'effects/audio/A05_oscilloscope.effect.ts', load: () => import('../../effects/audio/A05_oscilloscope.effect') },
  { meta: meta_A06, effectPath: 'effects/audio/A06_vu-meter.effect.tsx', load: () => import('../../effects/audio/A06_vu-meter.effect') },
  { meta: meta_A07, effectPath: 'effects/audio/A07_waveform-line.effect.tsx', load: () => import('../../effects/audio/A07_waveform-line.effect') },
  { meta: meta_A08, effectPath: 'effects/audio/A08_frequency-rings.effect.ts', load: () => import('../../effects/audio/A08_frequency-rings.effect') },
  { meta: meta_A09, effectPath: 'effects/audio/A09_amplitude-warp.effect.ts', load: () => import('../../effects/audio/A09_amplitude-warp.effect') },
  { meta: meta_A10, effectPath: 'effects/audio/A10_beat-cut.effect.tsx', load: () => import('../../effects/audio/A10_beat-cut.effect') },
  { meta: meta_B09, effectPath: 'effects/broadcast/B09_news-ticker.effect.tsx', load: () => import('../../effects/broadcast/B09_news-ticker.effect') },
  { meta: meta_B10, effectPath: 'effects/broadcast/B10_countdown-clock.effect.tsx', load: () => import('../../effects/broadcast/B10_countdown-clock.effect') },
  { meta: meta_B11, effectPath: 'effects/broadcast/B11_hud-frame.effect.tsx', load: () => import('../../effects/broadcast/B11_hud-frame.effect') },
  { meta: meta_B12, effectPath: 'effects/broadcast/B12_live-badge.effect.tsx', load: () => import('../../effects/broadcast/B12_live-badge.effect') },
  { meta: meta_B13, effectPath: 'effects/broadcast/B13_quote-card.effect.tsx', load: () => import('../../effects/broadcast/B13_quote-card.effect') },
  { meta: meta_B14, effectPath: 'effects/broadcast/B14_stat-callout.effect.tsx', load: () => import('../../effects/broadcast/B14_stat-callout.effect') },
  { meta: meta_B15, effectPath: 'effects/broadcast/B15_locator-pin.effect.tsx', load: () => import('../../effects/broadcast/B15_locator-pin.effect') },
  { meta: meta_B16, effectPath: 'effects/broadcast/B16_weather-panel.effect.tsx', load: () => import('../../effects/broadcast/B16_weather-panel.effect') },
  { meta: meta_C01, effectPath: 'effects/camera/C01_parallax-layers.effect.tsx', load: () => import('../../effects/camera/C01_parallax-layers.effect') },
  { meta: meta_C02, effectPath: 'effects/camera/C02_ken-burns.effect.tsx', load: () => import('../../effects/camera/C02_ken-burns.effect') },
  { meta: meta_C03, effectPath: 'effects/camera/C03_handheld-shake.effect.tsx', load: () => import('../../effects/camera/C03_handheld-shake.effect') },
  { meta: meta_C04, effectPath: 'effects/camera/C04_dolly-zoom.effect.tsx', load: () => import('../../effects/camera/C04_dolly-zoom.effect') },
  { meta: meta_C05, effectPath: 'effects/camera/C05_rack-focus.effect.tsx', load: () => import('../../effects/camera/C05_rack-focus.effect') },
  { meta: meta_C06, effectPath: 'effects/camera/C06_orbit-around.effect.tsx', load: () => import('../../effects/camera/C06_orbit-around.effect') },
  { meta: meta_C07, effectPath: 'effects/camera/C07_crash-zoom.effect.tsx', load: () => import('../../effects/camera/C07_crash-zoom.effect') },
  { meta: meta_C08, effectPath: 'effects/camera/C08_tilt-shift.effect.ts', load: () => import('../../effects/camera/C08_tilt-shift.effect') },
  { meta: meta_C09, effectPath: 'effects/camera/C09_roll-horizon.effect.tsx', load: () => import('../../effects/camera/C09_roll-horizon.effect') },
  { meta: meta_C10, effectPath: 'effects/camera/C10_depth-layers-3d.effect.tsx', load: () => import('../../effects/camera/C10_depth-layers-3d.effect') },
  { meta: meta_C11, effectPath: 'effects/camera/C11_perspective-card.effect.tsx', load: () => import('../../effects/camera/C11_perspective-card.effect') },
  { meta: meta_C12, effectPath: 'effects/camera/C12_follow-track.effect.tsx', load: () => import('../../effects/camera/C12_follow-track.effect') },
  { meta: meta_D01, effectPath: 'effects/distort/D01_displacement-wave.effect.ts', load: () => import('../../effects/distort/D01_displacement-wave.effect') },
  { meta: meta_D02, effectPath: 'effects/distort/D02_ripple-circle.effect.ts', load: () => import('../../effects/distort/D02_ripple-circle.effect') },
  { meta: meta_D03, effectPath: 'effects/distort/D03_twirl-vortex.effect.ts', load: () => import('../../effects/distort/D03_twirl-vortex.effect') },
  { meta: meta_D04, effectPath: 'effects/distort/D04_bulge-pinch.effect.ts', load: () => import('../../effects/distort/D04_bulge-pinch.effect') },
  { meta: meta_D05, effectPath: 'effects/distort/D05_wave-shear.effect.ts', load: () => import('../../effects/distort/D05_wave-shear.effect') },
  { meta: meta_D06, effectPath: 'effects/distort/D06_lens-barrel.effect.ts', load: () => import('../../effects/distort/D06_lens-barrel.effect') },
  { meta: meta_D07, effectPath: 'effects/distort/D07_mesh-warp.effect.ts', load: () => import('../../effects/distort/D07_mesh-warp.effect') },
  { meta: meta_D08, effectPath: 'effects/distort/D08_melt-drip.effect.ts', load: () => import('../../effects/distort/D08_melt-drip.effect') },
  { meta: meta_D09, effectPath: 'effects/distort/D09_turbulent-noise.effect.ts', load: () => import('../../effects/distort/D09_turbulent-noise.effect') },
  { meta: meta_D10, effectPath: 'effects/distort/D10_fisheye.effect.ts', load: () => import('../../effects/distort/D10_fisheye.effect') },
  { meta: meta_D11, effectPath: 'effects/distort/D11_mirror-fold.effect.ts', load: () => import('../../effects/distort/D11_mirror-fold.effect') },
  { meta: meta_D12, effectPath: 'effects/distort/D12_kaleidoscope.effect.ts', load: () => import('../../effects/distort/D12_kaleidoscope.effect') },
  { meta: meta_D13, effectPath: 'effects/distort/D13_polar-coord.effect.ts', load: () => import('../../effects/distort/D13_polar-coord.effect') },
  { meta: meta_D14, effectPath: 'effects/distort/D14_time-displace.effect.ts', load: () => import('../../effects/distort/D14_time-displace.effect') },
  { meta: meta_E01, effectPath: 'effects/texture/E01_film-grain.effect.ts', load: () => import('../../effects/texture/E01_film-grain.effect') },
  { meta: meta_E02, effectPath: 'effects/texture/E02_halftone-dot.effect.ts', load: () => import('../../effects/texture/E02_halftone-dot.effect') },
  { meta: meta_E03, effectPath: 'effects/texture/E03_dither-bayer.effect.ts', load: () => import('../../effects/texture/E03_dither-bayer.effect') },
  { meta: meta_E04, effectPath: 'effects/texture/E04_paper-fiber.effect.ts', load: () => import('../../effects/texture/E04_paper-fiber.effect') },
  { meta: meta_E05, effectPath: 'effects/texture/E05_scan-print.effect.ts', load: () => import('../../effects/texture/E05_scan-print.effect') },
  { meta: meta_E06, effectPath: 'effects/texture/E06_duotone-map.effect.tsx', load: () => import('../../effects/texture/E06_duotone-map.effect') },
  { meta: meta_E07, effectPath: 'effects/texture/E07_posterize-step.effect.ts', load: () => import('../../effects/texture/E07_posterize-step.effect') },
  { meta: meta_E08, effectPath: 'effects/texture/E08_cross-hatch.effect.ts', load: () => import('../../effects/texture/E08_cross-hatch.effect') },
  { meta: meta_E09, effectPath: 'effects/texture/E09_risograph.effect.ts', load: () => import('../../effects/texture/E09_risograph.effect') },
  { meta: meta_E10, effectPath: 'effects/texture/E10_vignette-breathe.effect.tsx', load: () => import('../../effects/texture/E10_vignette-breathe.effect') },
  { meta: meta_E11, effectPath: 'effects/texture/E11_chromatic-grain.effect.ts', load: () => import('../../effects/texture/E11_chromatic-grain.effect') },
  { meta: meta_E12, effectPath: 'effects/texture/E12_ascii-map.effect.ts', load: () => import('../../effects/texture/E12_ascii-map.effect') },
  { meta: meta_G01, effectPath: 'effects/glitch/G01_rgb-split.effect.tsx', load: () => import('../../effects/glitch/G01_rgb-split.effect') },
  { meta: meta_G02, effectPath: 'effects/glitch/G02_datamosh-slice.effect.ts', load: () => import('../../effects/glitch/G02_datamosh-slice.effect') },
  { meta: meta_G03, effectPath: 'effects/glitch/G03_crt-scanline.effect.ts', load: () => import('../../effects/glitch/G03_crt-scanline.effect') },
  { meta: meta_G04, effectPath: 'effects/glitch/G04_signal-loss.effect.ts', load: () => import('../../effects/glitch/G04_signal-loss.effect') },
  { meta: meta_G05, effectPath: 'effects/glitch/G05_vhs-tracking.effect.ts', load: () => import('../../effects/glitch/G05_vhs-tracking.effect') },
  { meta: meta_G06, effectPath: 'effects/glitch/G06_pixel-sort.effect.ts', load: () => import('../../effects/glitch/G06_pixel-sort.effect') },
  { meta: meta_G07, effectPath: 'effects/glitch/G07_block-corrupt.effect.ts', load: () => import('../../effects/glitch/G07_block-corrupt.effect') },
  { meta: meta_G08, effectPath: 'effects/glitch/G08_bit-crush.effect.ts', load: () => import('../../effects/glitch/G08_bit-crush.effect') },
  { meta: meta_G09, effectPath: 'effects/glitch/G09_interlace-tear.effect.ts', load: () => import('../../effects/glitch/G09_interlace-tear.effect') },
  { meta: meta_G10, effectPath: 'effects/glitch/G10_ghost-echo.effect.tsx', load: () => import('../../effects/glitch/G10_ghost-echo.effect') },
  { meta: meta_G11, effectPath: 'effects/glitch/G11_compression-artifact.effect.ts', load: () => import('../../effects/glitch/G11_compression-artifact.effect') },
  { meta: meta_G12, effectPath: 'effects/glitch/G12_sync-roll.effect.tsx', load: () => import('../../effects/glitch/G12_sync-roll.effect') },
  { meta: meta_G13, effectPath: 'effects/glitch/G13_color-bleed.effect.ts', load: () => import('../../effects/glitch/G13_color-bleed.effect') },
  { meta: meta_G14, effectPath: 'effects/glitch/G14_static-burst.effect.ts', load: () => import('../../effects/glitch/G14_static-burst.effect') },
  { meta: meta_G15, effectPath: 'effects/glitch/G15_frame-drop.effect.tsx', load: () => import('../../effects/glitch/G15_frame-drop.effect') },
  { meta: meta_G16, effectPath: 'effects/glitch/G16_chromatic-shear.effect.ts', load: () => import('../../effects/glitch/G16_chromatic-shear.effect') },
  { meta: meta_L01, effectPath: 'effects/light/L01_bloom-pulse.effect.tsx', load: () => import('../../effects/light/L01_bloom-pulse.effect') },
  { meta: meta_L02, effectPath: 'effects/light/L02_specular-sweep.effect.tsx', load: () => import('../../effects/light/L02_specular-sweep.effect') },
  { meta: meta_L03, effectPath: 'effects/light/L03_neon-flicker.effect.tsx', load: () => import('../../effects/light/L03_neon-flicker.effect') },
  { meta: meta_L04, effectPath: 'effects/light/L04_anamorphic-flare.effect.ts', load: () => import('../../effects/light/L04_anamorphic-flare.effect') },
  { meta: meta_L05, effectPath: 'effects/light/L05_god-rays.effect.ts', load: () => import('../../effects/light/L05_god-rays.effect') },
  { meta: meta_L06, effectPath: 'effects/light/L06_light-leak.effect.tsx', load: () => import('../../effects/light/L06_light-leak.effect') },
  { meta: meta_L07, effectPath: 'effects/light/L07_caustics.effect.ts', load: () => import('../../effects/light/L07_caustics.effect') },
  { meta: meta_L08, effectPath: 'effects/light/L08_lightning-arc.effect.ts', load: () => import('../../effects/light/L08_lightning-arc.effect') },
  { meta: meta_L09, effectPath: 'effects/light/L09_strobe-cut.effect.tsx', load: () => import('../../effects/light/L09_strobe-cut.effect') },
  { meta: meta_L10, effectPath: 'effects/light/L10_rim-light.effect.tsx', load: () => import('../../effects/light/L10_rim-light.effect') },
  { meta: meta_L11, effectPath: 'effects/light/L11_halation.effect.tsx', load: () => import('../../effects/light/L11_halation.effect') },
  { meta: meta_L12, effectPath: 'effects/light/L12_spotlight-track.effect.tsx', load: () => import('../../effects/light/L12_spotlight-track.effect') },
  { meta: meta_L13, effectPath: 'effects/light/L13_glow-trail.effect.ts', load: () => import('../../effects/light/L13_glow-trail.effect') },
  { meta: meta_L14, effectPath: 'effects/light/L14_prism-refract.effect.ts', load: () => import('../../effects/light/L14_prism-refract.effect') },
  { meta: meta_M01, effectPath: 'effects/mask/M01_shape-reveal.effect.tsx', load: () => import('../../effects/mask/M01_shape-reveal.effect') },
  { meta: meta_M02, effectPath: 'effects/mask/M02_gradient-wipe.effect.tsx', load: () => import('../../effects/mask/M02_gradient-wipe.effect') },
  { meta: meta_M03, effectPath: 'effects/mask/M03_text-knockout.effect.tsx', load: () => import('../../effects/mask/M03_text-knockout.effect') },
  { meta: meta_M04, effectPath: 'effects/mask/M04_alpha-matte.effect.tsx', load: () => import('../../effects/mask/M04_alpha-matte.effect') },
  { meta: meta_M05, effectPath: 'effects/mask/M05_spotlight-mask.effect.tsx', load: () => import('../../effects/mask/M05_spotlight-mask.effect') },
  { meta: meta_M06, effectPath: 'effects/mask/M06_brush-stroke.effect.tsx', load: () => import('../../effects/mask/M06_brush-stroke.effect') },
  { meta: meta_M07, effectPath: 'effects/mask/M07_scribble-erase.effect.tsx', load: () => import('../../effects/mask/M07_scribble-erase.effect') },
  { meta: meta_M08, effectPath: 'effects/mask/M08_blind-reveal.effect.tsx', load: () => import('../../effects/mask/M08_blind-reveal.effect') },
  { meta: meta_M09, effectPath: 'effects/mask/M09_radial-unveil.effect.tsx', load: () => import('../../effects/mask/M09_radial-unveil.effect') },
  { meta: meta_M10, effectPath: 'effects/mask/M10_follow-mask.effect.tsx', load: () => import('../../effects/mask/M10_follow-mask.effect') },
  { meta: meta_M11, effectPath: 'effects/mask/M11_split-mask.effect.tsx', load: () => import('../../effects/mask/M11_split-mask.effect') },
  { meta: meta_M12, effectPath: 'effects/mask/M12_noise-dissolve.effect.ts', load: () => import('../../effects/mask/M12_noise-dissolve.effect') },
  { meta: meta_N01, effectPath: 'effects/nature/N01_fire-flame.effect.ts', load: () => import('../../effects/nature/N01_fire-flame.effect') },
  { meta: meta_N02, effectPath: 'effects/nature/N02_smoke-plume.effect.ts', load: () => import('../../effects/nature/N02_smoke-plume.effect') },
  { meta: meta_N03, effectPath: 'effects/nature/N03_water-surface.effect.ts', load: () => import('../../effects/nature/N03_water-surface.effect') },
  { meta: meta_N04, effectPath: 'effects/nature/N04_cloud-drift.effect.ts', load: () => import('../../effects/nature/N04_cloud-drift.effect') },
  { meta: meta_N05, effectPath: 'effects/nature/N05_rain-streak.effect.ts', load: () => import('../../effects/nature/N05_rain-streak.effect') },
  { meta: meta_N06, effectPath: 'effects/nature/N06_wind-grass.effect.tsx', load: () => import('../../effects/nature/N06_wind-grass.effect') },
  { meta: meta_N07, effectPath: 'effects/nature/N07_aurora-wave.effect.ts', load: () => import('../../effects/nature/N07_aurora-wave.effect') },
  { meta: meta_N08, effectPath: 'effects/nature/N08_lightning-storm.effect.ts', load: () => import('../../effects/nature/N08_lightning-storm.effect') },
  { meta: meta_N09, effectPath: 'effects/nature/N09_sand-flow.effect.ts', load: () => import('../../effects/nature/N09_sand-flow.effect') },
  { meta: meta_N10, effectPath: 'effects/nature/N10_bubble-rise.effect.ts', load: () => import('../../effects/nature/N10_bubble-rise.effect') },
  { meta: meta_N11, effectPath: 'effects/nature/N11_crystal-grow.effect.ts', load: () => import('../../effects/nature/N11_crystal-grow.effect') },
  { meta: meta_N12, effectPath: 'effects/nature/N12_erosion-fade.effect.ts', load: () => import('../../effects/nature/N12_erosion-fade.effect') },
  { meta: meta_O01, effectPath: 'effects/motion/O01_pop-in.effect.tsx', load: () => import('../../effects/motion/O01_pop-in.effect') },
  { meta: meta_O02, effectPath: 'effects/motion/O02_drop-bounce.effect.tsx', load: () => import('../../effects/motion/O02_drop-bounce.effect') },
  { meta: meta_O03, effectPath: 'effects/motion/O03_swing-in.effect.tsx', load: () => import('../../effects/motion/O03_swing-in.effect') },
  { meta: meta_O04, effectPath: 'effects/motion/O04_flip-reveal.effect.tsx', load: () => import('../../effects/motion/O04_flip-reveal.effect') },
  { meta: meta_O05, effectPath: 'effects/motion/O05_slide-snap.effect.tsx', load: () => import('../../effects/motion/O05_slide-snap.effect') },
  { meta: meta_O06, effectPath: 'effects/motion/O06_fold-unfold.effect.tsx', load: () => import('../../effects/motion/O06_fold-unfold.effect') },
  { meta: meta_O07, effectPath: 'effects/motion/O07_focus-pop.effect.tsx', load: () => import('../../effects/motion/O07_focus-pop.effect') },
  { meta: meta_O08, effectPath: 'effects/motion/O08_peel-in.effect.tsx', load: () => import('../../effects/motion/O08_peel-in.effect') },
  { meta: meta_O09, effectPath: 'effects/motion/O09_jelly-wobble.effect.tsx', load: () => import('../../effects/motion/O09_jelly-wobble.effect') },
  { meta: meta_O10, effectPath: 'effects/motion/O10_pendulum-swing.effect.tsx', load: () => import('../../effects/motion/O10_pendulum-swing.effect') },
  { meta: meta_O11, effectPath: 'effects/motion/O11_spring-chain.effect.tsx', load: () => import('../../effects/motion/O11_spring-chain.effect') },
  { meta: meta_O12, effectPath: 'effects/motion/O12_gravity-toss.effect.tsx', load: () => import('../../effects/motion/O12_gravity-toss.effect') },
  { meta: meta_O13, effectPath: 'effects/motion/O13_magnetic-snap.effect.tsx', load: () => import('../../effects/motion/O13_magnetic-snap.effect') },
  { meta: meta_O14, effectPath: 'effects/motion/O14_rubber-band.effect.tsx', load: () => import('../../effects/motion/O14_rubber-band.effect') },
  { meta: meta_O15, effectPath: 'effects/motion/O15_inertia-drift.effect.tsx', load: () => import('../../effects/motion/O15_inertia-drift.effect') },
  { meta: meta_O16, effectPath: 'effects/motion/O16_float-hover.effect.tsx', load: () => import('../../effects/motion/O16_float-hover.effect') },
  { meta: meta_O17, effectPath: 'effects/motion/O17_breathe-pulse.effect.tsx', load: () => import('../../effects/motion/O17_breathe-pulse.effect') },
  { meta: meta_O18, effectPath: 'effects/motion/O18_self-orbit.effect.tsx', load: () => import('../../effects/motion/O18_self-orbit.effect') },
  { meta: meta_O19, effectPath: 'effects/motion/O19_tilt-sway.effect.tsx', load: () => import('../../effects/motion/O19_tilt-sway.effect') },
  { meta: meta_O20, effectPath: 'effects/motion/O20_heartbeat.effect.tsx', load: () => import('../../effects/motion/O20_heartbeat.effect') },
  { meta: meta_O21, effectPath: 'effects/motion/O21_attention-shake.effect.tsx', load: () => import('../../effects/motion/O21_attention-shake.effect') },
  { meta: meta_O22, effectPath: 'effects/motion/O22_tada-burst.effect.tsx', load: () => import('../../effects/motion/O22_tada-burst.effect') },
  { meta: meta_O23, effectPath: 'effects/motion/O23_stamp-slam.effect.tsx', load: () => import('../../effects/motion/O23_stamp-slam.effect') },
  { meta: meta_O24, effectPath: 'effects/motion/O24_ring-focus.effect.tsx', load: () => import('../../effects/motion/O24_ring-focus.effect') },
  { meta: meta_O25, effectPath: 'effects/motion/O25_glitch-pop.effect.tsx', load: () => import('../../effects/motion/O25_glitch-pop.effect') },
  { meta: meta_P01, effectPath: 'effects/particle/P01_particle-burst.effect.ts', load: () => import('../../effects/particle/P01_particle-burst.effect') },
  { meta: meta_P02, effectPath: 'effects/particle/P02_confetti-rain.effect.ts', load: () => import('../../effects/particle/P02_confetti-rain.effect') },
  { meta: meta_P03, effectPath: 'effects/particle/P03_spark-shower.effect.ts', load: () => import('../../effects/particle/P03_spark-shower.effect') },
  { meta: meta_P04, effectPath: 'effects/particle/P04_dust-motes.effect.ts', load: () => import('../../effects/particle/P04_dust-motes.effect') },
  { meta: meta_P05, effectPath: 'effects/particle/P05_bokeh-drift.effect.tsx', load: () => import('../../effects/particle/P05_bokeh-drift.effect') },
  { meta: meta_P06, effectPath: 'effects/particle/P06_snow-fall.effect.ts', load: () => import('../../effects/particle/P06_snow-fall.effect') },
  { meta: meta_P07, effectPath: 'effects/particle/P07_ember-rise.effect.ts', load: () => import('../../effects/particle/P07_ember-rise.effect') },
  { meta: meta_P08, effectPath: 'effects/particle/P08_swarm-flock.effect.ts', load: () => import('../../effects/particle/P08_swarm-flock.effect') },
  { meta: meta_P09, effectPath: 'effects/particle/P09_magnetic-field.effect.ts', load: () => import('../../effects/particle/P09_magnetic-field.effect') },
  { meta: meta_P10, effectPath: 'effects/particle/P10_orbit-ring.effect.ts', load: () => import('../../effects/particle/P10_orbit-ring.effect') },
  { meta: meta_P11, effectPath: 'effects/particle/P11_trail-emitter.effect.ts', load: () => import('../../effects/particle/P11_trail-emitter.effect') },
  { meta: meta_P12, effectPath: 'effects/particle/P12_explosion-debris.effect.ts', load: () => import('../../effects/particle/P12_explosion-debris.effect') },
  { meta: meta_P13, effectPath: 'effects/particle/P13_attract-repel.effect.ts', load: () => import('../../effects/particle/P13_attract-repel.effect') },
  { meta: meta_P14, effectPath: 'effects/particle/P14_point-cloud-form.effect.ts', load: () => import('../../effects/particle/P14_point-cloud-form.effect') },
  { meta: meta_Q01, effectPath: 'effects/liquid/Q01_metaball-merge.effect.ts', load: () => import('../../effects/liquid/Q01_metaball-merge.effect') },
  { meta: meta_Q02, effectPath: 'effects/liquid/Q02_ink-diffuse.effect.ts', load: () => import('../../effects/liquid/Q02_ink-diffuse.effect') },
  { meta: meta_Q03, effectPath: 'effects/liquid/Q03_paint-splatter.effect.ts', load: () => import('../../effects/liquid/Q03_paint-splatter.effect') },
  { meta: meta_Q04, effectPath: 'effects/liquid/Q04_viscous-drip.effect.tsx', load: () => import('../../effects/liquid/Q04_viscous-drip.effect') },
  { meta: meta_Q05, effectPath: 'effects/liquid/Q05_fluid-sim.effect.ts', load: () => import('../../effects/liquid/Q05_fluid-sim.effect') },
  { meta: meta_Q06, effectPath: 'effects/liquid/Q06_wave-tank.effect.ts', load: () => import('../../effects/liquid/Q06_wave-tank.effect') },
  { meta: meta_Q07, effectPath: 'effects/liquid/Q07_oil-slick.effect.ts', load: () => import('../../effects/liquid/Q07_oil-slick.effect') },
  { meta: meta_Q08, effectPath: 'effects/liquid/Q08_gel-wobble.effect.tsx', load: () => import('../../effects/liquid/Q08_gel-wobble.effect') },
  { meta: meta_Q09, effectPath: 'effects/liquid/Q09_foam-bubble.effect.ts', load: () => import('../../effects/liquid/Q09_foam-bubble.effect') },
  { meta: meta_Q10, effectPath: 'effects/liquid/Q10_liquid-fill.effect.tsx', load: () => import('../../effects/liquid/Q10_liquid-fill.effect') },
  { meta: meta_R01, effectPath: 'effects/pattern/R01_perlin-field.effect.ts', load: () => import('../../effects/pattern/R01_perlin-field.effect') },
  { meta: meta_R02, effectPath: 'effects/pattern/R02_flow-field.effect.ts', load: () => import('../../effects/pattern/R02_flow-field.effect') },
  { meta: meta_R03, effectPath: 'effects/pattern/R03_cellular-automata.effect.ts', load: () => import('../../effects/pattern/R03_cellular-automata.effect') },
  { meta: meta_R04, effectPath: 'effects/pattern/R04_reaction-diffusion.effect.ts', load: () => import('../../effects/pattern/R04_reaction-diffusion.effect') },
  { meta: meta_R05, effectPath: 'effects/pattern/R05_moire-interference.effect.tsx', load: () => import('../../effects/pattern/R05_moire-interference.effect') },
  { meta: meta_R06, effectPath: 'effects/pattern/R06_wave-interference.effect.ts', load: () => import('../../effects/pattern/R06_wave-interference.effect') },
  { meta: meta_R07, effectPath: 'effects/pattern/R07_lissajous.effect.tsx', load: () => import('../../effects/pattern/R07_lissajous.effect') },
  { meta: meta_R08, effectPath: 'effects/pattern/R08_phyllotaxis.effect.ts', load: () => import('../../effects/pattern/R08_phyllotaxis.effect') },
  { meta: meta_R09, effectPath: 'effects/pattern/R09_maze-generate.effect.ts', load: () => import('../../effects/pattern/R09_maze-generate.effect') },
  { meta: meta_R10, effectPath: 'effects/pattern/R10_stripe-shift.effect.tsx', load: () => import('../../effects/pattern/R10_stripe-shift.effect') },
  { meta: meta_R11, effectPath: 'effects/pattern/R11_checker-flip.effect.tsx', load: () => import('../../effects/pattern/R11_checker-flip.effect') },
  { meta: meta_R12, effectPath: 'effects/pattern/R12_hex-grid-pulse.effect.tsx', load: () => import('../../effects/pattern/R12_hex-grid-pulse.effect') },
  { meta: meta_R13, effectPath: 'effects/pattern/R13_dot-matrix.effect.tsx', load: () => import('../../effects/pattern/R13_dot-matrix.effect') },
  { meta: meta_R14, effectPath: 'effects/pattern/R14_chladni-figure.effect.ts', load: () => import('../../effects/pattern/R14_chladni-figure.effect') },
  { meta: meta_S01, effectPath: 'effects/shape/S01_stroke-draw.effect.tsx', load: () => import('../../effects/shape/S01_stroke-draw.effect') },
  { meta: meta_S02, effectPath: 'effects/shape/S02_blob-morph.effect.tsx', load: () => import('../../effects/shape/S02_blob-morph.effect') },
  { meta: meta_S03, effectPath: 'effects/shape/S03_grid-wave.effect.tsx', load: () => import('../../effects/shape/S03_grid-wave.effect') },
  { meta: meta_S04, effectPath: 'effects/shape/S04_radar-sweep.effect.tsx', load: () => import('../../effects/shape/S04_radar-sweep.effect') },
  { meta: meta_S05, effectPath: 'effects/shape/S05_polygon-rotate.effect.tsx', load: () => import('../../effects/shape/S05_polygon-rotate.effect') },
  { meta: meta_S06, effectPath: 'effects/shape/S06_circle-pack.effect.ts', load: () => import('../../effects/shape/S06_circle-pack.effect') },
  { meta: meta_S07, effectPath: 'effects/shape/S07_voronoi-shatter.effect.ts', load: () => import('../../effects/shape/S07_voronoi-shatter.effect') },
  { meta: meta_S08, effectPath: 'effects/shape/S08_triangulate.effect.ts', load: () => import('../../effects/shape/S08_triangulate.effect') },
  { meta: meta_S09, effectPath: 'effects/shape/S09_spiral-unfold.effect.tsx', load: () => import('../../effects/shape/S09_spiral-unfold.effect') },
  { meta: meta_S10, effectPath: 'effects/shape/S10_fractal-branch.effect.ts', load: () => import('../../effects/shape/S10_fractal-branch.effect') },
  { meta: meta_S11, effectPath: 'effects/shape/S11_boolean-merge.effect.tsx', load: () => import('../../effects/shape/S11_boolean-merge.effect') },
  { meta: meta_S12, effectPath: 'effects/shape/S12_dash-march.effect.tsx', load: () => import('../../effects/shape/S12_dash-march.effect') },
  { meta: meta_S13, effectPath: 'effects/shape/S13_corner-trace.effect.tsx', load: () => import('../../effects/shape/S13_corner-trace.effect') },
  { meta: meta_S14, effectPath: 'effects/shape/S14_concentric-pulse.effect.tsx', load: () => import('../../effects/shape/S14_concentric-pulse.effect') },
  { meta: meta_S15, effectPath: 'effects/shape/S15_isometric-stack.effect.tsx', load: () => import('../../effects/shape/S15_isometric-stack.effect') },
  { meta: meta_S16, effectPath: 'effects/shape/S16_truchet-tile.effect.tsx', load: () => import('../../effects/shape/S16_truchet-tile.effect') },
  { meta: meta_T01, effectPath: 'effects/type/T01_kinetic-split.effect.tsx', load: () => import('../../effects/type/T01_kinetic-split.effect') },
  { meta: meta_T02, effectPath: 'effects/type/T02_scramble-decode.effect.tsx', load: () => import('../../effects/type/T02_scramble-decode.effect') },
  { meta: meta_T03, effectPath: 'effects/type/T03_odometer-roll.effect.tsx', load: () => import('../../effects/type/T03_odometer-roll.effect') },
  { meta: meta_T04, effectPath: 'effects/type/T04_mask-reveal.effect.tsx', load: () => import('../../effects/type/T04_mask-reveal.effect') },
  { meta: meta_T05, effectPath: 'effects/type/T05_typewriter-caret.effect.tsx', load: () => import('../../effects/type/T05_typewriter-caret.effect') },
  { meta: meta_T06, effectPath: 'effects/type/T06_word-cascade.effect.tsx', load: () => import('../../effects/type/T06_word-cascade.effect') },
  { meta: meta_T07, effectPath: 'effects/type/T07_variable-weight-morph.effect.tsx', load: () => import('../../effects/type/T07_variable-weight-morph.effect') },
  { meta: meta_T08, effectPath: 'effects/type/T08_text-path-flow.effect.tsx', load: () => import('../../effects/type/T08_text-path-flow.effect') },
  { meta: meta_T09, effectPath: 'effects/type/T09_char-flip-3d.effect.tsx', load: () => import('../../effects/type/T09_char-flip-3d.effect') },
  { meta: meta_T10, effectPath: 'effects/type/T10_highlight-sweep.effect.tsx', load: () => import('../../effects/type/T10_highlight-sweep.effect') },
  { meta: meta_T11, effectPath: 'effects/type/T11_stretch-squash.effect.tsx', load: () => import('../../effects/type/T11_stretch-squash.effect') },
  { meta: meta_T12, effectPath: 'effects/type/T12_vertical-roll.effect.tsx', load: () => import('../../effects/type/T12_vertical-roll.effect') },
  { meta: meta_T13, effectPath: 'effects/type/T13_outline-fill.effect.tsx', load: () => import('../../effects/type/T13_outline-fill.effect') },
  { meta: meta_T14, effectPath: 'effects/type/T14_letter-explode.effect.tsx', load: () => import('../../effects/type/T14_letter-explode.effect') },
  { meta: meta_T15, effectPath: 'effects/type/T15_wave-text.effect.tsx', load: () => import('../../effects/type/T15_wave-text.effect') },
  { meta: meta_T16, effectPath: 'effects/type/T16_justify-snap.effect.tsx', load: () => import('../../effects/type/T16_justify-snap.effect') },
  { meta: meta_T17, effectPath: 'effects/type/T17_char-bounce-wave.effect.tsx', load: () => import('../../effects/type/T17_char-bounce-wave.effect') },
  { meta: meta_T18, effectPath: 'effects/type/T18_char-swarm-assemble.effect.tsx', load: () => import('../../effects/type/T18_char-swarm-assemble.effect') },
  { meta: meta_T19, effectPath: 'effects/type/T19_word-swap-roll.effect.tsx', load: () => import('../../effects/type/T19_word-swap-roll.effect') },
  { meta: meta_T20, effectPath: 'effects/type/T20_char-gravity-fall.effect.tsx', load: () => import('../../effects/type/T20_char-gravity-fall.effect') },
  { meta: meta_T21, effectPath: 'effects/type/T21_elastic-tracking.effect.tsx', load: () => import('../../effects/type/T21_elastic-tracking.effect') },
  { meta: meta_U01, effectPath: 'effects/ui/U01_terminal-boot.effect.tsx', load: () => import('../../effects/ui/U01_terminal-boot.effect') },
  { meta: meta_U02, effectPath: 'effects/ui/U02_toggle-switch.effect.tsx', load: () => import('../../effects/ui/U02_toggle-switch.effect') },
  { meta: meta_U03, effectPath: 'effects/ui/U03_loading-spinner.effect.tsx', load: () => import('../../effects/ui/U03_loading-spinner.effect') },
  { meta: meta_U04, effectPath: 'effects/ui/U04_skeleton-shimmer.effect.tsx', load: () => import('../../effects/ui/U04_skeleton-shimmer.effect') },
  { meta: meta_U05, effectPath: 'effects/ui/U05_notification-stack.effect.tsx', load: () => import('../../effects/ui/U05_notification-stack.effect') },
  { meta: meta_U06, effectPath: 'effects/ui/U06_tab-slide.effect.tsx', load: () => import('../../effects/ui/U06_tab-slide.effect') },
  { meta: meta_U07, effectPath: 'effects/ui/U07_modal-spring.effect.tsx', load: () => import('../../effects/ui/U07_modal-spring.effect') },
  { meta: meta_U08, effectPath: 'effects/ui/U08_cursor-trace.effect.tsx', load: () => import('../../effects/ui/U08_cursor-trace.effect') },
  { meta: meta_U09, effectPath: 'effects/ui/U09_keyboard-press.effect.tsx', load: () => import('../../effects/ui/U09_keyboard-press.effect') },
  { meta: meta_U10, effectPath: 'effects/ui/U10_chip-filter.effect.tsx', load: () => import('../../effects/ui/U10_chip-filter.effect') },
  { meta: meta_U11, effectPath: 'effects/ui/U11_accordion-expand.effect.tsx', load: () => import('../../effects/ui/U11_accordion-expand.effect') },
  { meta: meta_U12, effectPath: 'effects/ui/U12_drag-sort.effect.tsx', load: () => import('../../effects/ui/U12_drag-sort.effect') },
  { meta: meta_V01, effectPath: 'effects/data/V01_bar-race.effect.tsx', load: () => import('../../effects/data/V01_bar-race.effect') },
  { meta: meta_V02, effectPath: 'effects/data/V02_counter-odometer.effect.tsx', load: () => import('../../effects/data/V02_counter-odometer.effect') },
  { meta: meta_V03, effectPath: 'effects/data/V03_progress-ring.effect.tsx', load: () => import('../../effects/data/V03_progress-ring.effect') },
  { meta: meta_V04, effectPath: 'effects/data/V04_line-chart-draw.effect.tsx', load: () => import('../../effects/data/V04_line-chart-draw.effect') },
  { meta: meta_V05, effectPath: 'effects/data/V05_pie-sweep.effect.tsx', load: () => import('../../effects/data/V05_pie-sweep.effect') },
  { meta: meta_V06, effectPath: 'effects/data/V06_sparkline-scroll.effect.tsx', load: () => import('../../effects/data/V06_sparkline-scroll.effect') },
  { meta: meta_V07, effectPath: 'effects/data/V07_heatmap-fill.effect.tsx', load: () => import('../../effects/data/V07_heatmap-fill.effect') },
  { meta: meta_V08, effectPath: 'effects/data/V08_node-graph.effect.tsx', load: () => import('../../effects/data/V08_node-graph.effect') },
  { meta: meta_V09, effectPath: 'effects/data/V09_gauge-needle.effect.tsx', load: () => import('../../effects/data/V09_gauge-needle.effect') },
  { meta: meta_V10, effectPath: 'effects/data/V10_stacked-grow.effect.tsx', load: () => import('../../effects/data/V10_stacked-grow.effect') },
  { meta: meta_V11, effectPath: 'effects/data/V11_scatter-settle.effect.ts', load: () => import('../../effects/data/V11_scatter-settle.effect') },
  { meta: meta_V12, effectPath: 'effects/data/V12_sankey-flow.effect.tsx', load: () => import('../../effects/data/V12_sankey-flow.effect') },
  { meta: meta_V13, effectPath: 'effects/data/V13_tree-expand.effect.tsx', load: () => import('../../effects/data/V13_tree-expand.effect') },
  { meta: meta_V14, effectPath: 'effects/data/V14_timeline-scrub.effect.tsx', load: () => import('../../effects/data/V14_timeline-scrub.effect') },
  { meta: meta_X01, effectPath: 'effects/trans/X01_iris-wipe.effect.tsx', load: () => import('../../effects/trans/X01_iris-wipe.effect') },
  { meta: meta_X02, effectPath: 'effects/trans/X02_slice-shuffle.effect.tsx', load: () => import('../../effects/trans/X02_slice-shuffle.effect') },
  { meta: meta_X03, effectPath: 'effects/trans/X03_zoom-punch.effect.tsx', load: () => import('../../effects/trans/X03_zoom-punch.effect') },
  { meta: meta_X04, effectPath: 'effects/trans/X04_ink-bleed.effect.tsx', load: () => import('../../effects/trans/X04_ink-bleed.effect') },
  { meta: meta_X05, effectPath: 'effects/trans/X05_push-slide.effect.tsx', load: () => import('../../effects/trans/X05_push-slide.effect') },
  { meta: meta_X06, effectPath: 'effects/trans/X06_clock-wipe.effect.tsx', load: () => import('../../effects/trans/X06_clock-wipe.effect') },
  { meta: meta_X07, effectPath: 'effects/trans/X07_page-curl.effect.ts', load: () => import('../../effects/trans/X07_page-curl.effect') },
  { meta: meta_X08, effectPath: 'effects/trans/X08_blinds.effect.tsx', load: () => import('../../effects/trans/X08_blinds.effect') },
  { meta: meta_X09, effectPath: 'effects/trans/X09_pixelate-cross.effect.ts', load: () => import('../../effects/trans/X09_pixelate-cross.effect') },
  { meta: meta_X10, effectPath: 'effects/trans/X10_morph-cut.effect.tsx', load: () => import('../../effects/trans/X10_morph-cut.effect') },
  { meta: meta_X11, effectPath: 'effects/trans/X11_shatter-break.effect.ts', load: () => import('../../effects/trans/X11_shatter-break.effect') },
  { meta: meta_X12, effectPath: 'effects/trans/X12_liquid-warp.effect.ts', load: () => import('../../effects/trans/X12_liquid-warp.effect') },
  { meta: meta_X13, effectPath: 'effects/trans/X13_cube-rotate.effect.tsx', load: () => import('../../effects/trans/X13_cube-rotate.effect') },
  { meta: meta_X14, effectPath: 'effects/trans/X14_whip-pan.effect.tsx', load: () => import('../../effects/trans/X14_whip-pan.effect') },
  { meta: meta_X15, effectPath: 'effects/trans/X15_luma-wipe.effect.ts', load: () => import('../../effects/trans/X15_luma-wipe.effect') },
  { meta: meta_X16, effectPath: 'effects/trans/X16_split-open.effect.tsx', load: () => import('../../effects/trans/X16_split-open.effect') },
  { meta: meta_Y07, effectPath: 'effects/stylize/Y07_ink-outline.effect.ts', load: () => import('../../effects/stylize/Y07_ink-outline.effect') },
  { meta: meta_Y08, effectPath: 'effects/stylize/Y08_hatch-shade.effect.ts', load: () => import('../../effects/stylize/Y08_hatch-shade.effect') },
  { meta: meta_Y09, effectPath: 'effects/stylize/Y09_stipple-dots.effect.ts', load: () => import('../../effects/stylize/Y09_stipple-dots.effect') },
  { meta: meta_Y10, effectPath: 'effects/stylize/Y10_mosaic-tiles.effect.ts', load: () => import('../../effects/stylize/Y10_mosaic-tiles.effect') },
  { meta: meta_Y11, effectPath: 'effects/stylize/Y11_stained-glass.effect.ts', load: () => import('../../effects/stylize/Y11_stained-glass.effect') },
  { meta: meta_Y12, effectPath: 'effects/stylize/Y12_paper-cutout.effect.tsx', load: () => import('../../effects/stylize/Y12_paper-cutout.effect') },
];
