// AUTO-GENERATED by scripts/gen-manifest.mjs — do not edit, do not commit conflicts by hand.
import type { FxKernel, FxMeta } from './types';

import meta_A01 from '../../effects/audio/A01_waveform-bars.meta';
import meta_A02 from '../../effects/audio/A02_spectrum-analyzer.meta';
import meta_A04 from '../../effects/audio/A04_beat-pulse.meta';
import meta_C01 from '../../effects/camera/C01_parallax-layers.meta';
import meta_C02 from '../../effects/camera/C02_ken-burns.meta';
import meta_C03 from '../../effects/camera/C03_handheld-shake.meta';
import meta_C04 from '../../effects/camera/C04_dolly-zoom.meta';
import meta_C05 from '../../effects/camera/C05_rack-focus.meta';
import meta_C07 from '../../effects/camera/C07_crash-zoom.meta';
import meta_C08 from '../../effects/camera/C08_tilt-shift.meta';
import meta_C11 from '../../effects/camera/C11_perspective-card.meta';
import meta_D01 from '../../effects/distort/D01_displacement-wave.meta';
import meta_D02 from '../../effects/distort/D02_ripple-circle.meta';
import meta_D03 from '../../effects/distort/D03_twirl-vortex.meta';
import meta_D05 from '../../effects/distort/D05_wave-shear.meta';
import meta_D11 from '../../effects/distort/D11_mirror-fold.meta';
import meta_E01 from '../../effects/texture/E01_film-grain.meta';
import meta_E02 from '../../effects/texture/E02_halftone-dot.meta';
import meta_E03 from '../../effects/texture/E03_dither-bayer.meta';
import meta_E06 from '../../effects/texture/E06_duotone-map.meta';
import meta_E07 from '../../effects/texture/E07_posterize-step.meta';
import meta_E10 from '../../effects/texture/E10_vignette-breathe.meta';
import meta_G01 from '../../effects/glitch/G01_rgb-split.meta';
import meta_G02 from '../../effects/glitch/G02_datamosh-slice.meta';
import meta_G03 from '../../effects/glitch/G03_crt-scanline.meta';
import meta_G04 from '../../effects/glitch/G04_signal-loss.meta';
import meta_G05 from '../../effects/glitch/G05_vhs-tracking.meta';
import meta_G06 from '../../effects/glitch/G06_pixel-sort.meta';
import meta_G07 from '../../effects/glitch/G07_block-corrupt.meta';
import meta_G08 from '../../effects/glitch/G08_bit-crush.meta';
import meta_G09 from '../../effects/glitch/G09_interlace-tear.meta';
import meta_G10 from '../../effects/glitch/G10_ghost-echo.meta';
import meta_G12 from '../../effects/glitch/G12_sync-roll.meta';
import meta_G14 from '../../effects/glitch/G14_static-burst.meta';
import meta_G15 from '../../effects/glitch/G15_frame-drop.meta';
import meta_L01 from '../../effects/light/L01_bloom-pulse.meta';
import meta_L02 from '../../effects/light/L02_specular-sweep.meta';
import meta_L03 from '../../effects/light/L03_neon-flicker.meta';
import meta_L04 from '../../effects/light/L04_anamorphic-flare.meta';
import meta_L05 from '../../effects/light/L05_god-rays.meta';
import meta_L06 from '../../effects/light/L06_light-leak.meta';
import meta_L08 from '../../effects/light/L08_lightning-arc.meta';
import meta_L09 from '../../effects/light/L09_strobe-cut.meta';
import meta_L12 from '../../effects/light/L12_spotlight-track.meta';
import meta_L13 from '../../effects/light/L13_glow-trail.meta';
import meta_M01 from '../../effects/mask/M01_shape-reveal.meta';
import meta_M02 from '../../effects/mask/M02_gradient-wipe.meta';
import meta_M03 from '../../effects/mask/M03_text-knockout.meta';
import meta_M05 from '../../effects/mask/M05_spotlight-mask.meta';
import meta_M09 from '../../effects/mask/M09_radial-unveil.meta';
import meta_M12 from '../../effects/mask/M12_noise-dissolve.meta';
import meta_N03 from '../../effects/nature/N03_water-surface.meta';
import meta_N05 from '../../effects/nature/N05_rain-streak.meta';
import meta_P01 from '../../effects/particle/P01_particle-burst.meta';
import meta_P02 from '../../effects/particle/P02_confetti-rain.meta';
import meta_P03 from '../../effects/particle/P03_spark-shower.meta';
import meta_P04 from '../../effects/particle/P04_dust-motes.meta';
import meta_P05 from '../../effects/particle/P05_bokeh-drift.meta';
import meta_P06 from '../../effects/particle/P06_snow-fall.meta';
import meta_P07 from '../../effects/particle/P07_ember-rise.meta';
import meta_P08 from '../../effects/particle/P08_swarm-flock.meta';
import meta_P09 from '../../effects/particle/P09_magnetic-field.meta';
import meta_P10 from '../../effects/particle/P10_orbit-ring.meta';
import meta_P11 from '../../effects/particle/P11_trail-emitter.meta';
import meta_Q01 from '../../effects/liquid/Q01_metaball-merge.meta';
import meta_Q08 from '../../effects/liquid/Q08_gel-wobble.meta';
import meta_Q10 from '../../effects/liquid/Q10_liquid-fill.meta';
import meta_R01 from '../../effects/pattern/R01_perlin-field.meta';
import meta_R05 from '../../effects/pattern/R05_moire-interference.meta';
import meta_R07 from '../../effects/pattern/R07_lissajous.meta';
import meta_R08 from '../../effects/pattern/R08_phyllotaxis.meta';
import meta_R10 from '../../effects/pattern/R10_stripe-shift.meta';
import meta_R11 from '../../effects/pattern/R11_checker-flip.meta';
import meta_R13 from '../../effects/pattern/R13_dot-matrix.meta';
import meta_S01 from '../../effects/shape/S01_stroke-draw.meta';
import meta_S02 from '../../effects/shape/S02_blob-morph.meta';
import meta_S03 from '../../effects/shape/S03_grid-wave.meta';
import meta_S04 from '../../effects/shape/S04_radar-sweep.meta';
import meta_S05 from '../../effects/shape/S05_polygon-rotate.meta';
import meta_S09 from '../../effects/shape/S09_spiral-unfold.meta';
import meta_S12 from '../../effects/shape/S12_dash-march.meta';
import meta_S13 from '../../effects/shape/S13_corner-trace.meta';
import meta_S14 from '../../effects/shape/S14_concentric-pulse.meta';
import meta_T01 from '../../effects/type/T01_kinetic-split.meta';
import meta_T02 from '../../effects/type/T02_scramble-decode.meta';
import meta_T03 from '../../effects/type/T03_odometer-roll.meta';
import meta_T04 from '../../effects/type/T04_mask-reveal.meta';
import meta_T05 from '../../effects/type/T05_typewriter-caret.meta';
import meta_T06 from '../../effects/type/T06_word-cascade.meta';
import meta_T09 from '../../effects/type/T09_char-flip-3d.meta';
import meta_T10 from '../../effects/type/T10_highlight-sweep.meta';
import meta_T15 from '../../effects/type/T15_wave-text.meta';
import meta_U01 from '../../effects/ui/U01_terminal-boot.meta';
import meta_U02 from '../../effects/ui/U02_toggle-switch.meta';
import meta_U03 from '../../effects/ui/U03_loading-spinner.meta';
import meta_U04 from '../../effects/ui/U04_skeleton-shimmer.meta';
import meta_V01 from '../../effects/data/V01_bar-race.meta';
import meta_V02 from '../../effects/data/V02_counter-odometer.meta';
import meta_V03 from '../../effects/data/V03_progress-ring.meta';
import meta_V04 from '../../effects/data/V04_line-chart-draw.meta';
import meta_V05 from '../../effects/data/V05_pie-sweep.meta';
import meta_V09 from '../../effects/data/V09_gauge-needle.meta';
import meta_X01 from '../../effects/trans/X01_iris-wipe.meta';
import meta_X02 from '../../effects/trans/X02_slice-shuffle.meta';
import meta_X03 from '../../effects/trans/X03_zoom-punch.meta';
import meta_X04 from '../../effects/trans/X04_ink-bleed.meta';
import meta_X05 from '../../effects/trans/X05_push-slide.meta';
import meta_X06 from '../../effects/trans/X06_clock-wipe.meta';
import meta_X08 from '../../effects/trans/X08_blinds.meta';
import meta_X09 from '../../effects/trans/X09_pixelate-cross.meta';
import meta_X12 from '../../effects/trans/X12_liquid-warp.meta';
import meta_X13 from '../../effects/trans/X13_cube-rotate.meta';
import meta_X14 from '../../effects/trans/X14_whip-pan.meta';
import meta_X15 from '../../effects/trans/X15_luma-wipe.meta';
import meta_X16 from '../../effects/trans/X16_split-open.meta';

export interface ManifestEntry {
  meta: FxMeta;
  /** repo-relative path of the effect file (key for source loading) */
  effectPath: string;
  load: () => Promise<{ default: FxKernel }>;
}

export const manifest: ManifestEntry[] = [
  { meta: meta_A01, effectPath: 'effects/audio/A01_waveform-bars.effect.ts', load: () => import('../../effects/audio/A01_waveform-bars.effect') },
  { meta: meta_A02, effectPath: 'effects/audio/A02_spectrum-analyzer.effect.ts', load: () => import('../../effects/audio/A02_spectrum-analyzer.effect') },
  { meta: meta_A04, effectPath: 'effects/audio/A04_beat-pulse.effect.tsx', load: () => import('../../effects/audio/A04_beat-pulse.effect') },
  { meta: meta_C01, effectPath: 'effects/camera/C01_parallax-layers.effect.tsx', load: () => import('../../effects/camera/C01_parallax-layers.effect') },
  { meta: meta_C02, effectPath: 'effects/camera/C02_ken-burns.effect.tsx', load: () => import('../../effects/camera/C02_ken-burns.effect') },
  { meta: meta_C03, effectPath: 'effects/camera/C03_handheld-shake.effect.tsx', load: () => import('../../effects/camera/C03_handheld-shake.effect') },
  { meta: meta_C04, effectPath: 'effects/camera/C04_dolly-zoom.effect.tsx', load: () => import('../../effects/camera/C04_dolly-zoom.effect') },
  { meta: meta_C05, effectPath: 'effects/camera/C05_rack-focus.effect.tsx', load: () => import('../../effects/camera/C05_rack-focus.effect') },
  { meta: meta_C07, effectPath: 'effects/camera/C07_crash-zoom.effect.tsx', load: () => import('../../effects/camera/C07_crash-zoom.effect') },
  { meta: meta_C08, effectPath: 'effects/camera/C08_tilt-shift.effect.ts', load: () => import('../../effects/camera/C08_tilt-shift.effect') },
  { meta: meta_C11, effectPath: 'effects/camera/C11_perspective-card.effect.tsx', load: () => import('../../effects/camera/C11_perspective-card.effect') },
  { meta: meta_D01, effectPath: 'effects/distort/D01_displacement-wave.effect.ts', load: () => import('../../effects/distort/D01_displacement-wave.effect') },
  { meta: meta_D02, effectPath: 'effects/distort/D02_ripple-circle.effect.ts', load: () => import('../../effects/distort/D02_ripple-circle.effect') },
  { meta: meta_D03, effectPath: 'effects/distort/D03_twirl-vortex.effect.ts', load: () => import('../../effects/distort/D03_twirl-vortex.effect') },
  { meta: meta_D05, effectPath: 'effects/distort/D05_wave-shear.effect.ts', load: () => import('../../effects/distort/D05_wave-shear.effect') },
  { meta: meta_D11, effectPath: 'effects/distort/D11_mirror-fold.effect.ts', load: () => import('../../effects/distort/D11_mirror-fold.effect') },
  { meta: meta_E01, effectPath: 'effects/texture/E01_film-grain.effect.ts', load: () => import('../../effects/texture/E01_film-grain.effect') },
  { meta: meta_E02, effectPath: 'effects/texture/E02_halftone-dot.effect.ts', load: () => import('../../effects/texture/E02_halftone-dot.effect') },
  { meta: meta_E03, effectPath: 'effects/texture/E03_dither-bayer.effect.ts', load: () => import('../../effects/texture/E03_dither-bayer.effect') },
  { meta: meta_E06, effectPath: 'effects/texture/E06_duotone-map.effect.tsx', load: () => import('../../effects/texture/E06_duotone-map.effect') },
  { meta: meta_E07, effectPath: 'effects/texture/E07_posterize-step.effect.ts', load: () => import('../../effects/texture/E07_posterize-step.effect') },
  { meta: meta_E10, effectPath: 'effects/texture/E10_vignette-breathe.effect.tsx', load: () => import('../../effects/texture/E10_vignette-breathe.effect') },
  { meta: meta_G01, effectPath: 'effects/glitch/G01_rgb-split.effect.tsx', load: () => import('../../effects/glitch/G01_rgb-split.effect') },
  { meta: meta_G02, effectPath: 'effects/glitch/G02_datamosh-slice.effect.ts', load: () => import('../../effects/glitch/G02_datamosh-slice.effect') },
  { meta: meta_G03, effectPath: 'effects/glitch/G03_crt-scanline.effect.ts', load: () => import('../../effects/glitch/G03_crt-scanline.effect') },
  { meta: meta_G04, effectPath: 'effects/glitch/G04_signal-loss.effect.ts', load: () => import('../../effects/glitch/G04_signal-loss.effect') },
  { meta: meta_G05, effectPath: 'effects/glitch/G05_vhs-tracking.effect.ts', load: () => import('../../effects/glitch/G05_vhs-tracking.effect') },
  { meta: meta_G06, effectPath: 'effects/glitch/G06_pixel-sort.effect.ts', load: () => import('../../effects/glitch/G06_pixel-sort.effect') },
  { meta: meta_G07, effectPath: 'effects/glitch/G07_block-corrupt.effect.ts', load: () => import('../../effects/glitch/G07_block-corrupt.effect') },
  { meta: meta_G08, effectPath: 'effects/glitch/G08_bit-crush.effect.ts', load: () => import('../../effects/glitch/G08_bit-crush.effect') },
  { meta: meta_G09, effectPath: 'effects/glitch/G09_interlace-tear.effect.ts', load: () => import('../../effects/glitch/G09_interlace-tear.effect') },
  { meta: meta_G10, effectPath: 'effects/glitch/G10_ghost-echo.effect.tsx', load: () => import('../../effects/glitch/G10_ghost-echo.effect') },
  { meta: meta_G12, effectPath: 'effects/glitch/G12_sync-roll.effect.tsx', load: () => import('../../effects/glitch/G12_sync-roll.effect') },
  { meta: meta_G14, effectPath: 'effects/glitch/G14_static-burst.effect.ts', load: () => import('../../effects/glitch/G14_static-burst.effect') },
  { meta: meta_G15, effectPath: 'effects/glitch/G15_frame-drop.effect.tsx', load: () => import('../../effects/glitch/G15_frame-drop.effect') },
  { meta: meta_L01, effectPath: 'effects/light/L01_bloom-pulse.effect.tsx', load: () => import('../../effects/light/L01_bloom-pulse.effect') },
  { meta: meta_L02, effectPath: 'effects/light/L02_specular-sweep.effect.tsx', load: () => import('../../effects/light/L02_specular-sweep.effect') },
  { meta: meta_L03, effectPath: 'effects/light/L03_neon-flicker.effect.tsx', load: () => import('../../effects/light/L03_neon-flicker.effect') },
  { meta: meta_L04, effectPath: 'effects/light/L04_anamorphic-flare.effect.ts', load: () => import('../../effects/light/L04_anamorphic-flare.effect') },
  { meta: meta_L05, effectPath: 'effects/light/L05_god-rays.effect.ts', load: () => import('../../effects/light/L05_god-rays.effect') },
  { meta: meta_L06, effectPath: 'effects/light/L06_light-leak.effect.tsx', load: () => import('../../effects/light/L06_light-leak.effect') },
  { meta: meta_L08, effectPath: 'effects/light/L08_lightning-arc.effect.ts', load: () => import('../../effects/light/L08_lightning-arc.effect') },
  { meta: meta_L09, effectPath: 'effects/light/L09_strobe-cut.effect.tsx', load: () => import('../../effects/light/L09_strobe-cut.effect') },
  { meta: meta_L12, effectPath: 'effects/light/L12_spotlight-track.effect.tsx', load: () => import('../../effects/light/L12_spotlight-track.effect') },
  { meta: meta_L13, effectPath: 'effects/light/L13_glow-trail.effect.ts', load: () => import('../../effects/light/L13_glow-trail.effect') },
  { meta: meta_M01, effectPath: 'effects/mask/M01_shape-reveal.effect.tsx', load: () => import('../../effects/mask/M01_shape-reveal.effect') },
  { meta: meta_M02, effectPath: 'effects/mask/M02_gradient-wipe.effect.tsx', load: () => import('../../effects/mask/M02_gradient-wipe.effect') },
  { meta: meta_M03, effectPath: 'effects/mask/M03_text-knockout.effect.tsx', load: () => import('../../effects/mask/M03_text-knockout.effect') },
  { meta: meta_M05, effectPath: 'effects/mask/M05_spotlight-mask.effect.tsx', load: () => import('../../effects/mask/M05_spotlight-mask.effect') },
  { meta: meta_M09, effectPath: 'effects/mask/M09_radial-unveil.effect.tsx', load: () => import('../../effects/mask/M09_radial-unveil.effect') },
  { meta: meta_M12, effectPath: 'effects/mask/M12_noise-dissolve.effect.ts', load: () => import('../../effects/mask/M12_noise-dissolve.effect') },
  { meta: meta_N03, effectPath: 'effects/nature/N03_water-surface.effect.ts', load: () => import('../../effects/nature/N03_water-surface.effect') },
  { meta: meta_N05, effectPath: 'effects/nature/N05_rain-streak.effect.ts', load: () => import('../../effects/nature/N05_rain-streak.effect') },
  { meta: meta_P01, effectPath: 'effects/particle/P01_particle-burst.effect.ts', load: () => import('../../effects/particle/P01_particle-burst.effect') },
  { meta: meta_P02, effectPath: 'effects/particle/P02_confetti-rain.effect.ts', load: () => import('../../effects/particle/P02_confetti-rain.effect') },
  { meta: meta_P03, effectPath: 'effects/particle/P03_spark-shower.effect.ts', load: () => import('../../effects/particle/P03_spark-shower.effect') },
  { meta: meta_P04, effectPath: 'effects/particle/P04_dust-motes.effect.ts', load: () => import('../../effects/particle/P04_dust-motes.effect') },
  { meta: meta_P05, effectPath: 'effects/particle/P05_bokeh-drift.effect.tsx', load: () => import('../../effects/particle/P05_bokeh-drift.effect') },
  { meta: meta_P06, effectPath: 'effects/particle/P06_snow-fall.effect.ts', load: () => import('../../effects/particle/P06_snow-fall.effect') },
  { meta: meta_P07, effectPath: 'effects/particle/P07_ember-rise.effect.ts', load: () => import('../../effects/particle/P07_ember-rise.effect') },
  { meta: meta_P08, effectPath: 'effects/particle/P08_swarm-flock.effect.ts', load: () => import('../../effects/particle/P08_swarm-flock.effect') },
  { meta: meta_P09, effectPath: 'effects/particle/P09_magnetic-field.effect.ts', load: () => import('../../effects/particle/P09_magnetic-field.effect') },
  { meta: meta_P10, effectPath: 'effects/particle/P10_orbit-ring.effect.ts', load: () => import('../../effects/particle/P10_orbit-ring.effect') },
  { meta: meta_P11, effectPath: 'effects/particle/P11_trail-emitter.effect.ts', load: () => import('../../effects/particle/P11_trail-emitter.effect') },
  { meta: meta_Q01, effectPath: 'effects/liquid/Q01_metaball-merge.effect.ts', load: () => import('../../effects/liquid/Q01_metaball-merge.effect') },
  { meta: meta_Q08, effectPath: 'effects/liquid/Q08_gel-wobble.effect.tsx', load: () => import('../../effects/liquid/Q08_gel-wobble.effect') },
  { meta: meta_Q10, effectPath: 'effects/liquid/Q10_liquid-fill.effect.tsx', load: () => import('../../effects/liquid/Q10_liquid-fill.effect') },
  { meta: meta_R01, effectPath: 'effects/pattern/R01_perlin-field.effect.ts', load: () => import('../../effects/pattern/R01_perlin-field.effect') },
  { meta: meta_R05, effectPath: 'effects/pattern/R05_moire-interference.effect.tsx', load: () => import('../../effects/pattern/R05_moire-interference.effect') },
  { meta: meta_R07, effectPath: 'effects/pattern/R07_lissajous.effect.tsx', load: () => import('../../effects/pattern/R07_lissajous.effect') },
  { meta: meta_R08, effectPath: 'effects/pattern/R08_phyllotaxis.effect.ts', load: () => import('../../effects/pattern/R08_phyllotaxis.effect') },
  { meta: meta_R10, effectPath: 'effects/pattern/R10_stripe-shift.effect.tsx', load: () => import('../../effects/pattern/R10_stripe-shift.effect') },
  { meta: meta_R11, effectPath: 'effects/pattern/R11_checker-flip.effect.tsx', load: () => import('../../effects/pattern/R11_checker-flip.effect') },
  { meta: meta_R13, effectPath: 'effects/pattern/R13_dot-matrix.effect.tsx', load: () => import('../../effects/pattern/R13_dot-matrix.effect') },
  { meta: meta_S01, effectPath: 'effects/shape/S01_stroke-draw.effect.tsx', load: () => import('../../effects/shape/S01_stroke-draw.effect') },
  { meta: meta_S02, effectPath: 'effects/shape/S02_blob-morph.effect.tsx', load: () => import('../../effects/shape/S02_blob-morph.effect') },
  { meta: meta_S03, effectPath: 'effects/shape/S03_grid-wave.effect.tsx', load: () => import('../../effects/shape/S03_grid-wave.effect') },
  { meta: meta_S04, effectPath: 'effects/shape/S04_radar-sweep.effect.tsx', load: () => import('../../effects/shape/S04_radar-sweep.effect') },
  { meta: meta_S05, effectPath: 'effects/shape/S05_polygon-rotate.effect.tsx', load: () => import('../../effects/shape/S05_polygon-rotate.effect') },
  { meta: meta_S09, effectPath: 'effects/shape/S09_spiral-unfold.effect.tsx', load: () => import('../../effects/shape/S09_spiral-unfold.effect') },
  { meta: meta_S12, effectPath: 'effects/shape/S12_dash-march.effect.tsx', load: () => import('../../effects/shape/S12_dash-march.effect') },
  { meta: meta_S13, effectPath: 'effects/shape/S13_corner-trace.effect.tsx', load: () => import('../../effects/shape/S13_corner-trace.effect') },
  { meta: meta_S14, effectPath: 'effects/shape/S14_concentric-pulse.effect.tsx', load: () => import('../../effects/shape/S14_concentric-pulse.effect') },
  { meta: meta_T01, effectPath: 'effects/type/T01_kinetic-split.effect.tsx', load: () => import('../../effects/type/T01_kinetic-split.effect') },
  { meta: meta_T02, effectPath: 'effects/type/T02_scramble-decode.effect.tsx', load: () => import('../../effects/type/T02_scramble-decode.effect') },
  { meta: meta_T03, effectPath: 'effects/type/T03_odometer-roll.effect.tsx', load: () => import('../../effects/type/T03_odometer-roll.effect') },
  { meta: meta_T04, effectPath: 'effects/type/T04_mask-reveal.effect.tsx', load: () => import('../../effects/type/T04_mask-reveal.effect') },
  { meta: meta_T05, effectPath: 'effects/type/T05_typewriter-caret.effect.tsx', load: () => import('../../effects/type/T05_typewriter-caret.effect') },
  { meta: meta_T06, effectPath: 'effects/type/T06_word-cascade.effect.tsx', load: () => import('../../effects/type/T06_word-cascade.effect') },
  { meta: meta_T09, effectPath: 'effects/type/T09_char-flip-3d.effect.tsx', load: () => import('../../effects/type/T09_char-flip-3d.effect') },
  { meta: meta_T10, effectPath: 'effects/type/T10_highlight-sweep.effect.tsx', load: () => import('../../effects/type/T10_highlight-sweep.effect') },
  { meta: meta_T15, effectPath: 'effects/type/T15_wave-text.effect.tsx', load: () => import('../../effects/type/T15_wave-text.effect') },
  { meta: meta_U01, effectPath: 'effects/ui/U01_terminal-boot.effect.tsx', load: () => import('../../effects/ui/U01_terminal-boot.effect') },
  { meta: meta_U02, effectPath: 'effects/ui/U02_toggle-switch.effect.tsx', load: () => import('../../effects/ui/U02_toggle-switch.effect') },
  { meta: meta_U03, effectPath: 'effects/ui/U03_loading-spinner.effect.tsx', load: () => import('../../effects/ui/U03_loading-spinner.effect') },
  { meta: meta_U04, effectPath: 'effects/ui/U04_skeleton-shimmer.effect.tsx', load: () => import('../../effects/ui/U04_skeleton-shimmer.effect') },
  { meta: meta_V01, effectPath: 'effects/data/V01_bar-race.effect.tsx', load: () => import('../../effects/data/V01_bar-race.effect') },
  { meta: meta_V02, effectPath: 'effects/data/V02_counter-odometer.effect.tsx', load: () => import('../../effects/data/V02_counter-odometer.effect') },
  { meta: meta_V03, effectPath: 'effects/data/V03_progress-ring.effect.tsx', load: () => import('../../effects/data/V03_progress-ring.effect') },
  { meta: meta_V04, effectPath: 'effects/data/V04_line-chart-draw.effect.tsx', load: () => import('../../effects/data/V04_line-chart-draw.effect') },
  { meta: meta_V05, effectPath: 'effects/data/V05_pie-sweep.effect.tsx', load: () => import('../../effects/data/V05_pie-sweep.effect') },
  { meta: meta_V09, effectPath: 'effects/data/V09_gauge-needle.effect.tsx', load: () => import('../../effects/data/V09_gauge-needle.effect') },
  { meta: meta_X01, effectPath: 'effects/trans/X01_iris-wipe.effect.tsx', load: () => import('../../effects/trans/X01_iris-wipe.effect') },
  { meta: meta_X02, effectPath: 'effects/trans/X02_slice-shuffle.effect.tsx', load: () => import('../../effects/trans/X02_slice-shuffle.effect') },
  { meta: meta_X03, effectPath: 'effects/trans/X03_zoom-punch.effect.tsx', load: () => import('../../effects/trans/X03_zoom-punch.effect') },
  { meta: meta_X04, effectPath: 'effects/trans/X04_ink-bleed.effect.tsx', load: () => import('../../effects/trans/X04_ink-bleed.effect') },
  { meta: meta_X05, effectPath: 'effects/trans/X05_push-slide.effect.tsx', load: () => import('../../effects/trans/X05_push-slide.effect') },
  { meta: meta_X06, effectPath: 'effects/trans/X06_clock-wipe.effect.tsx', load: () => import('../../effects/trans/X06_clock-wipe.effect') },
  { meta: meta_X08, effectPath: 'effects/trans/X08_blinds.effect.tsx', load: () => import('../../effects/trans/X08_blinds.effect') },
  { meta: meta_X09, effectPath: 'effects/trans/X09_pixelate-cross.effect.ts', load: () => import('../../effects/trans/X09_pixelate-cross.effect') },
  { meta: meta_X12, effectPath: 'effects/trans/X12_liquid-warp.effect.ts', load: () => import('../../effects/trans/X12_liquid-warp.effect') },
  { meta: meta_X13, effectPath: 'effects/trans/X13_cube-rotate.effect.tsx', load: () => import('../../effects/trans/X13_cube-rotate.effect') },
  { meta: meta_X14, effectPath: 'effects/trans/X14_whip-pan.effect.tsx', load: () => import('../../effects/trans/X14_whip-pan.effect') },
  { meta: meta_X15, effectPath: 'effects/trans/X15_luma-wipe.effect.ts', load: () => import('../../effects/trans/X15_luma-wipe.effect') },
  { meta: meta_X16, effectPath: 'effects/trans/X16_split-open.effect.tsx', load: () => import('../../effects/trans/X16_split-open.effect') },
];
